FROM ubuntu:latest
LABEL maintainer="ravendra tiwari ravendra.tiwari75@gmail.com"

# Set environment variables
ENV TOMCAT_VERSION 9
ENV JAVA_HOME /usr/lib/jvm/java-18-openjdk-amd64

# Install JDK & wget packages.
RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install openjdk-18-jdk wget

# Install and configure Tomcat.
RUN mkdir /opt/tomcat
WORKDIR /opt/tomcat
ADD https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.80/bin/apache-tomcat-9.0.80.tar.gz .
RUN tar -xvzf apache-tomcat-9.0.80.tar.gz
RUN mv apache-tomcat-9.0.80/* /opt/tomcat
EXPOSE 8080
COPY ./sample.war /opt/tomcat/webapps
CMD ["/opt/tomcat/bin/catalina.sh", "run"]

