apiVersion: v1
kind: Service
metadata:
  name: nginx-service   # any name
spec:
  selector:
    app: nginx    # Apply this service to any pods which has the specific label
  ports:
    - port: 8080   # containers port expose
      targetPort: 80  # pods port
      nodePort: 31200  # any port. this is optional, there is no need because we have specify service type LoadBalancer
  type: LoadBalancer